-- +goose Up
-- +goose StatementBegin
CREATE TABLE reservations (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            BIGINT      NOT NULL REFERENCES products(sku),
    count          INT         NOT NULL,
    reserved_until TIMESTAMPTZ NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE reservations;
-- +goose StatementEnd
